# Generated by Django 4.2.23 on 2025-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
